In [1]:
import pandas as pd
df = pd.read_csv(r'C:\Users\BHAVANIPRASADKARRI\OneDrive\Desktop\jupyter notebook\weather_data.csv')
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
NEW SPITNET CODES

In [2]:
df .columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='str')

In [3]:
df ["event"]

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: str

In [4]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [5]:
df[['event','day', 'temperature']]

   event       day  temperature
0   Rain  1/1/2017           32
1  Sunny  1/2/2017           35
2   Snow  1/3/2017           28
3   Snow  1/4/2017           24
4   Rain  1/5/2017           32
5  Sunny  1/6/2017           31

In [6]:
df ['temperature'].max()

np.int64(35)

In [7]:
df ['temperature'].min()

np.int64(24)

In [14]:
df ['temperature'].std()

np.float64(3.8297084310253524)

In [15]:
df.describe

<bound method NDFrame.describe of         day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny>

In [17]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [18]:
df [df.temperature>= 32]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain

In [26]:
df [df.temperature == df.temperature.max()]
 #df[df.temperature ==df['temperature'].max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [28]:
df['day'][df.temperature ==df['temperature'].max()]

1    1/2/2017
Name: day, dtype: str

In [30]:
df[['day','temperature']][df.temperature ==df['temperature'].max()]

        day  temperature
1  1/2/2017           35

In [31]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [32]:
df . index

RangeIndex(start=0, stop=6, step=1)

In [35]:
df.set_index('day')

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [43]:
df.set_index('day',inplace=True)

KeyError: "None of ['day'] are in the columns"

In [40]:
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [ ]:
18.06