In [6]:
import pandas as pd
weather_data  = [
    {'day': '1/1/2026' , 'tempeature': 34 , 'windspeed': 6 ,'event':'Rain'},
    {'day': '1/2/2026' , 'tempeature': 35 , 'windspeed': 7 ,'event':'Sunny'},
    {'day': '1/3/2026' , 'tempeature': 28 , 'windspeed': 2 ,'event':'Snow'},
        
]
df = pd.DataFrame(weather_data)
df

        day  tempeature  windspeed  event
0  1/1/2026          34          6   Rain
1  1/2/2026          35          7  Sunny
2  1/3/2026          28          2   Snow

In [ ]:
# 4:READING WEITING CSV ,EXCEL FILES
TOPICS:
 1.Read csv 
 2.Write csv
 3.Read excel
 4.Write excel

In [9]:
df = pd.read_csv("stock_data.csv")
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [10]:
df = pd . read_csv("stock_data.csv")
df

  stocks data     Unnamed: 1 Unnamed: 2 Unnamed: 3     Unnamed: 4
0     tickers            eps    revenue      price         people
1       GOOGL          27.82         87        845     larry page
2         WMT           4.61        484         65           n.a.
3        MSFT             -1         85         64     bill gates
4        RIL   not available         50       1023  mukesh ambani
5        TATA            5.6         -1       n.a.     ratan tata

In [11]:
df = pd .read_csv("stock_data.csv",skip_rows=1)
df # skip_rows=1-------skiprows=1

TypeError: read_csv() got an unexpected keyword argument 'skip_rows'. Did you mean 'skiprows'?

In [12]:
df = pd .read_csv("stock_data.csv",skiprows=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [13]:
df = pd .read_csv("stock_data.csv",header=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [17]:
df = pd . read_csv ("stock_data.csv",header=None)
df

       0              1    2     3              4
0  GOOGL          27.82   87   845     larry page
1    WMT           4.61  484    65           n.a.
2   MSFT             -1   85    64     bill gates
3   RIL   not available   50  1023  mukesh ambani
4   TATA            5.6   -1  n.a.     ratan tata

In [18]:
df = pd . read_csv ("stock_data.csv",header=None,name=["Ticker","Eps","Revenue","Price","People"])
df # name ---------names

TypeError: read_csv() got an unexpected keyword argument 'name'. Did you mean 'names'?

In [19]:
df = pd . read_csv ("stock_data.csv",header=None,names=["Ticker","Eps","Revenue","Price","People"])
df                                                                         #6 mins

  Ticker            Eps  Revenue Price         People
0  GOOGL          27.82       87   845     larry page
1    WMT           4.61      484    65           n.a.
2   MSFT             -1       85    64     bill gates
3   RIL   not available       50  1023  mukesh ambani
4   TATA            5.6       -1  n.a.     ratan tata