In [1]:
import pandas as pd
df = pd.read_csv("stock_data.csv")
df

  GOOGL          27.82   87   845     larry page
0   WMT           4.61  484    65           n.a.
1  MSFT             -1   85    64     bill gates
2  RIL   not available   50  1023  mukesh ambani
3  TATA            5.6   -1  n.a.     ratan tata

In [3]:
df = pd.read_csv ("stock_data.csv", nrows=1)
df

  GOOGL  27.82   87  845 larry page
0   WMT   4.61  484   65       n.a.

In [5]:
df = pd.read_csv ("stock_data.csv", na_values=["not available" ,"n.a."])
df

  GOOGL  27.82   87     845     larry page
0   WMT   4.61  484    65.0            NaN
1  MSFT  -1.00   85    64.0     bill gates
2  RIL     NaN   50  1023.0  mukesh ambani
3  TATA   5.60   -1     NaN     ratan tata

In [11]:
df = pd.read_csv ("stock_data.csv", nrows=3)
df

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.
2    MSFT  -1.00       85     64  bill gates

In [7]:
df =  pd.read_csv ("stock_data.csv",na_values = {

_IncompleteInputError: incomplete input (1215405583.py, line 1)

In [15]:
df =  pd.read_csv ("stock_data.csv",na_values = {
               'eps ': ["not available" , "n.a."],
               'revenue':["not available" , "n.a.",-1],
               'people':["not available" , "n.a."]
})
df

  tickers            eps  revenue price         people
0   GOOGL          27.82     87.0   845     larry page
1     WMT           4.61    484.0    65            NaN
2    MSFT             -1     85.0    64     bill gates
3    RIL   not available     50.0  1023  mukesh ambani
4    TATA            5.6      NaN  n.a.     ratan tata

In [17]:
df =  pd.read_csv ("stock_data.csv",na_values = {
               'eps': ["not available" , "n.a."],
               'revenue':["not available" , "n.a.",-1],
               'people':["not available" , "n.a."]
})
df

  tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     WMT   4.61    484.0    65            NaN
2    MSFT  -1.00     85.0    64     bill gates
3    RIL     NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

In [18]:
df . to_csv('new.csv')

In [19]:
df.to_csv('new.csv',index=False)

PermissionError: [Errno 13] Permission denied: 'new.csv'

In [20]:
df.to_csv('new.csv',index=False)

In [ ]:
                                                                ----13:15 mins